### ISSUE TITLE
how to get a conversational TTS datasets?

### ISSUE THREAD

**Issue by hertz-pj** [keonlee9420/Emotional-FastSpeech2#10]
hi，Conversational tts seems to have no relevant open source dataset, do you have a method to obtain the relevant dataset. Or do you have any other suggestions?

**Comment by keonlee9420** [comment]
Hi @hertz-pj , thank you for your attention. I think you can use IEMOCAP for that since it keeps the turn information (dialog is in its order).

**Comment by keonlee9420** [comment]
close due to inactivity
