### ISSUE TITLE
Training MFA problem

### ISSUE THREAD

**Issue by martin3252** [keonlee9420/Emotional-FastSpeech2#11]
Firstly, thanks for sharing this great repo.
I encountered two errors when I was training MFA with IEMOCAP dataset.
The are the same errors and as following:
`ERROR (gmm-est-fmllr[5.5.985]:FindKeyInternal():util/kaldi-table-inl.h:2106) You provided  the "cs" option but are not calling with keys in sorted order.`

Have you encountered these errors before? Besides, I've already searched these errors on Montreal-Forced-Aligner github and couldn't find the solution.
   
My MFA version is 2.0.0b7

**Comment by keonlee9420** [comment]
Hi @martin3252, it seems to be related to the kaldi issue. You can search issues in the official [repo](https://github.com/kaldi-asr/kaldi). I recommend reinstalling kaldi and then retrying the process.

**Comment by keonlee9420** [comment]
close due to inactivity
