### ISSUE TITLE
How to download AIHub Multimodal Video AI datasets?

### ISSUE THREAD

**Issue by youngsuen** [keonlee9420/Emotional-FastSpeech2#7]
Hi, I am in China, how can I downlaod dataset from AIHub Multimodal Video AI datasets?

**Comment by keonlee9420** [comment]
Hi @youngsuen , sorry for the late reply. Unfortunately, I don't have any idea for that. Maybe asking them directly through an official email would help you.

**Comment by keonlee9420** [comment]
close due to inactivity
