### ISSUE TITLE
Mechanical noise

### ISSUE THREAD

**Issue by MrYANG23** [keonlee9420/Emotional-FastSpeech2#8]
hi nice work, I have a issue，how to resolve Mechanical noise，no matter FastSpeech2 or this repo，there always exiest Mechanical noise

**Comment by keonlee9420** [comment]
Hi @MrYANG23 , what do you mean by 'Mechanical noise'?

**Comment by bagustris** [comment]
Hi @keonlee9420,

Maybe what he meant by mechanical noise is like in the following file,
https://www.dropbox.com/s/0jo0largys117cz/That%27s%20out%20of%20control_Ses01M_ang.wav?dl=0

In my case, I only heard the noise only. My setup is the default one in IEMOCAP dataset.
Any idea?

**Comment by keonlee9420** [comment]
Ah, I see. It is mainly originated from the dataset (especially IEMOCAP). There is a few options from my experience:
1. the currently shared vocoder is not trained on IEMOCAP, so you can fine-tune it on IEMOCAP and/or model output.
2. you can also utilize speech enhancement to denoise them. I tried [FullSubNet](https://github.com/keonlee9420/FullSubNet), and it showed somewhat cleared audio.
3. of course, the best way to this end is preparing super studio-clear quality audio. But I know it is not an easy task in general.

**Comment by MrYANG23** [comment]
> Ah, I see. It is mainly originated from the dataset (especially IEMOCAP). There is a few options from my experience:
> 
> 1. the currently shared vocoder is not trained on IEMOCAP, so you can fine-tune it on IEMOCAP and/or model output.
> 2. you can also utilize speech enhancement to denoise them. I tried [FullSubNet](https://github.com/keonlee9420/FullSubNet), and it showed somewhat cleared audio.
> 3. of course, the best way to this end is preparing super studio-clear quality audio. But I know it is not an easy task in general.

thank your reply ,yes what I mean like this issue https://github.com/ming024/FastSpeech2/issues/76

**Comment by keonlee9420** [comment]
close due to inactivity
